name: Monitor AliExpress

on:
  schedule:
    - cron: '0 */1 * * *'  # Roda a cada 1 hora
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run monitor
      run: python monitor.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        PRODUCT_URL: ${{ secrets.PRODUCT_URL }}
    
    - name: Commit logs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add price_log.txt
        git commit -m "Update price log" || echo "No changes to commit"
        git push
